"""create goals table

Revision ID: a4e453b8446f
Revises: 44b9828208db
Create Date: 2026-08-05 18:15:45.004849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4e453b8446f'
down_revision: Union[str, Sequence[str], None] = '44b9828208db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index('ix_transactions_account_date', 'transactions', ['account_id', 'transaction_date'], unique=False)
    op.create_index('ix_transactions_category', 'transactions', ['category_id'], unique=False)
    op.create_index('ix_transactions_date', 'transactions', ['transaction_date'], unique=False)
    op.create_index('ix_transactions_merchant', 'transactions', ['merchant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_merchant', table_name='transactions')
    op.drop_index('ix_transactions_date', table_name='transactions')
    op.drop_index('ix_transactions_category', table_name='transactions')
    op.drop_index('ix_transactions_account_date', table_name='transactions')
    op.drop_column('transactions', 'updated_at')
    # ### end Alembic commands ###
